#!/usr/bin/bash
echo -e "\e[34m---- Disks ----\e[0m"
disks=($(fdisk -l | grep "Disk /" | awk '{print $2}' | rev | cut -c 2- | rev))
for index in "${!disks[@]}"; do
    echo "$index: ${disks[$index]}"
done
echo -n "Select a disk: "; read index
if [ $index -lt 0 ] || [ $index -gt $(( ${#disks[@]} - 1 )) ]; then
	echo -e "\e[31mInvalid input\e[0m"
	exit
fi
disk=${disks[index]}
echo -e "\e[32mSelected disk $disk\e[0m\n"

echo -e "\e[34m---- Partitions ----\e[0m"
sector_size=$(fdisk -l $disk | grep optimal | rev | awk '{print $2}' | rev)
boot_end=$(( (268435456 / $sector_size) + 2047 ))
swap_end=$(( ($(free -b | grep Mem: | awk '{print $2}') / $sector_size) + $boot_end ))
(echo g; echo n; echo; echo 2048; echo $boot_end; echo t; echo 1; echo n; echo; echo $(( $boot_end + 1 )); echo $swap_end; echo p; echo q;) | fdisk $disk