#!/usr/bin/bash

# Disks
echo -e "\e[34m---- Disks ----\e[0m"
disks=($(fdisk -l | grep "Disk /" | awk '{print $2}' | rev | cut -c 2- | rev))
while true; do
	for index in "${!disks[@]}"; do
			echo "$index: ${disks[$index]}"
	done
	echo -n "Select a disk: "; read index
	if [ $index -gt -1 ] && [ $index -lt ${#disks[@]} ]; then
		disk=${disks[index]}
		echo -e "\e[32mSelected disk $disk\e[0m\n"
		break
	fi
done

# Partitions
echo -e "\e[34m---- Partitions ----\e[0m"
sector_size=$(fdisk -l $disk | grep optimal | rev | awk '{print $2}' | rev)
boot_end=$(( (268435456 / $sector_size) + 2047 ))
swap_end=$(( ($(free -b | grep Mem: | awk '{print $2}') / $sector_size) + $boot_end ))
(
	echo g; echo n; echo; echo 2048; echo $boot_end; echo t; echo 1;
	echo n; echo; echo $(( $boot_end + 1 )); echo $swap_end; echo t; echo 2; echo 19;
	echo n; echo; echo $(( $swap_end + 1 )); echo -0;
	echo p; echo q; # change to write later
) | fdisk $disk &> /dev/null
echo -e "\e[32mCreated boot partition\e[0m"
echo -e "\e[32mCreated swap partition\e[0m"
echo -e "\e[32mCreated root partition\e[0m\n"

# Filesystems
echo -e "\e[34m---- Filesystems ----\e[0m"
partitions=($(fdisk -l $disk | grep ^/dev | awk '{print $1}'))
# mkfs.vfat -F 32 -n boot ${partitions[0]}
# mkswap -L swap ${partitions[1]}

# f2fs, ext4, jfs, nilfs2, xfs